local Color, colors, Group, groups, styles = require('colorbuddy').setup()

-- Set up primary and secondary colour palette
-- These are the main flavour colours
Color.new('primary', '#ff0088')
Color.new('secondary', '#56c5cc')

-- Set up semantic colour palette
-- These are to be used sparingly, but have semantic meaning for things like lsp diagnostics, git diffs, etc.
Color.new('diagnostic_error', '#ff0088')
Color.new('diagnostic_warning', '#f7aa1c')
Color.new('diagnostic_info', '#56c5cc')
Color.new('diagnostic_hint', '#a8f6f8')
Color.new('diff_add', '#56c5cc')
Color.new('diff_change', '#f7aa1c')
Color.new('diff_delete', '#ff0088')

-- Set up greyscale palette
-- The rest of the theme is based on this greyscale palette, hence the name 'noir' buddy
Color.new('black', '#121212')
Color.new('grey_9', '#212121')
Color.new('grey_8', '#323232')
Color.new('grey_7', '#535353')
Color.new('grey_6', '#737373')
Color.new('grey_5', '#949494')
Color.new('grey_4', '#a7a7a7')
Color.new('grey_3', '#b4b4b4')
Color.new('grey_2', '#d5d5d5')
Color.new('grey_1', '#f5f5f5')
Color.new('white', '#ffffff')

-- Generic Highlighting
Group.new('Normal', colors.white, colors.black)
Group.new('Search', colors.white, colors.secondary)
Group.new('IncSearch', colors.white, colors.primary)
Group.new('Visual', nil, colors.grey_8)
Group.new('SignColumn', nil, nil)
Group.new('LineNr', colors.grey_8, nil)
Group.new('CursorLineNr', colors.grey_6, nil)
  -- TODO... This section needs work for sure

-- Treesitter Syntax Highlighting
-- See :help treesitter-highlight-groups
Group.new('@text.literal', colors.grey_2)
Group.new('@text.reference', colors.grey_2)
Group.new('@text.title', colors.grey_2)
Group.new('@text.uri', colors.grey_2)
Group.new('@text.underline', colors.grey_2)
Group.new('@text.todo', colors.grey_2)
Group.new('@comment', colors.grey_7)
Group.new('@punctuation', colors.grey_2)
Group.new('@punctuation.bracket', colors.grey_2)
Group.new('@punctuation.delimiter', colors.grey_2)
Group.new('@constant', colors.grey_2)
Group.new('@constant.builtin', colors.grey_2)
Group.new('@constant.macro', colors.grey_2)
Group.new('@define', colors.grey_2)
Group.new('@macro', colors.grey_2)
Group.new('@string', colors.grey_2)
Group.new('@string.escape', colors.grey_2)
Group.new('@string.special', colors.grey_2)
Group.new('@character', colors.grey_2)
Group.new('@character.special', colors.grey_2)
Group.new('@number', colors.grey_2)
Group.new('@boolean', colors.grey_2)
Group.new('@float', colors.grey_2)
Group.new('@function', colors.grey_2)
Group.new('@function.call', colors.grey_2)
Group.new('@function.builtin', colors.grey_2)
Group.new('@function.macro', colors.grey_2)
Group.new('@parameter', colors.grey_2)
Group.new('@method', colors.grey_2)
Group.new('@method.call', colors.grey_2)
Group.new('@field', colors.grey_2)
Group.new('@property', colors.grey_2)
Group.new('@constructor', colors.grey_2)
Group.new('@conditional', colors.grey_2)
Group.new('@repeat', colors.grey_2)
Group.new('@label', colors.grey_2)
Group.new('@operator', colors.grey_2)
Group.new('@keyword', colors.grey_2)
Group.new('@keyword.function', colors.grey_2)
Group.new('@keyword.return', colors.grey_2)
Group.new('@keyword.operator', colors.grey_2)
Group.new('@exception', colors.grey_2)
Group.new('@variable', colors.grey_2)
Group.new('@variable.builtin', colors.grey_2)
Group.new('@type', colors.grey_2)
Group.new('@type.definition', colors.grey_2)
Group.new('@storageclass', colors.grey_2)
Group.new('@structure', colors.grey_2)
Group.new('@namespace', colors.grey_2)
Group.new('@include', colors.grey_2)
Group.new('@preproc', colors.grey_2)
Group.new('@debug', colors.grey_2)
Group.new('@tag', colors.grey_2)
  -- TODO... This section needs work for sure

-- Semantic Highlighting
Group.new('DiagnosticError', colors.diagnostic_error, nil, styles.italic + styles.undercurl)
Group.new('DiagnosticWarning', colors.diagnostic_warning, nil, styles.italic + styles.undercurl)
Group.new('DiagnosticInfo', colors.diagnostic_info, nil, styles.italic + styles.undercurl)
Group.new('DiagnosticHint', colors.diagnostic_hint, nil, styles.italic + styles.undercurl)
Group.new('DiagnosticSignError', colors.diagnostic_error)
Group.new('DiagnosticSignWarning', colors.diagnostic_warning)
Group.new('DiagnosticSignInfo', colors.diagnostic_info)
Group.new('DiagnosticSignHint', colors.diagnostic_hint)
Group.new('DiffAdd', colors.diff_add)
Group.new('DiffChange', colors.diff_change)
Group.new('DiffDelete', colors.diff_delete)
