local Group = require('colorbuddy').Group
local colors = require('colorbuddy').colors
local styles = require('colorbuddy').styles

-- Generic Highlighting
Group.new('Normal', colors.gray_4, colors.bgcolor)
Group.new('Search', colors.black, colors.white)
Group.new('IncSearch', colors.black, colors.white)
Group.new('Visual', nil, colors.gray_8)
Group.new('SignColumn', nil, colors.bgcolor)
Group.new('LineNr', colors.gray_8, colors.bgcolor)

Group.new('Comment', colors.gray_7)
Group.new('Constant', colors.primary)
Group.new('Character', colors.gray_5)
Group.new('Identifier', colors.white)
Group.new('Statement', colors.gray_1)
Group.new('PreProc', colors.primary)
Group.new('Type', colors.gray_6)
Group.new('Special', colors.gray_5)
Group.new('Error', colors.primary)
Group.new('Todo', colors.primary, colors.gray_8)
Group.new('Function', colors.primary)

Group.new('ColorColumn', nil, colors.gray_8)
Group.new('Conceal', colors.gray_7)
Group.new('Cursor', colors.black)
Group.new('CursorColumn', colors.gray_8)
Group.new('CursorLine', nil, colors.gray_9)
Group.new('CursorLineNr', colors.gray_6, colors.gray_9)
Group.new('Directory', colors.gray_10)
Group.new('DiffAdd', colors.primary, colors.gray_8)
Group.new('DiffChange', colors.white, colors.gray_8)
Group.new('DiffDelete', colors.secondary, colors.gray_8)
Group.new('DiffText', colors.white, colors.gray_7)
Group.new('ErrorMsg', colors.gray_1, colors.primary)
Group.new('VertSplit', colors.black, colors.gray_9)

Group.new('Folded', colors.gray_5, colors.gray_8)
Group.new('FoldColumn', colors.gray_5, colors.gray_8)
Group.new('MatchParen', nil, colors.gray_7)
Group.new('MoreMsg', colors.black, colors.gray_11)
Group.new('NonText', colors.gray_8, colors.black)
Group.new('Pmenu', colors.gray_2, colors.gray_8)
Group.new('PmenuSel', colors.gray_11, colors.gray_8)
Group.new('PmenuSbar', colors.primary, colors.gray_8)
Group.new('PmenuThumb', colors.primary, colors.gray_7)
Group.new('Question', colors.gray_1, colors.gray_8)
Group.new('SpecialKey', colors.gray_6, colors.black)
Group.new('SpellBad', colors.primary)
Group.new('SpellCap', colors.white)
Group.new('SpellLocal', colors.gray_5)
Group.new('SpellRare', colors.primary)
Group.new('StatusLine', colors.gray_5, colors.gray_8)
Group.new('TabLine', colors.gray_3, colors.gray_8)
Group.new('TabLineFill', nil, colors.gray_8)
Group.new('TabLineSel', colors.gray_2, colors.black)
Group.new('Title', colors.gray_10)
Group.new('VisualNOS', colors.primary, colors.gray_8)
Group.new('WarningMsg', colors.primary)
Group.new('WildMenu', colors.gray_5, colors.gray_8)
-- TODO... This section needs work for sure

-- Treesitter Syntax Highlighting
-- See :help treesitter-highlight-groups
Group.new('@include', colors.gray_6)
Group.new('@keyword', colors.gray_5)
Group.new('@variable', colors.gray_2)
Group.new('@punctuation.delimiter', colors.gray_6)
Group.new('@punctuation.special', colors.primary)
Group.new('@type.builtin', colors.gray_6)
Group.new('@tag', colors.gray_6)
Group.new('@tag.attribute', colors.gray_4)
Group.new('@constructor', colors.gray_1)
Group.new('@property', colors.gray_2)
Group.new('@method', colors.gray_1)
Group.new('@keyword.return', colors.white)
Group.new('@keyword.function', colors.gray_5)
Group.new('@function', colors.white)
Group.new('@none', colors.gray_3)
Group.new('@punctuation.bracket', colors.gray_6)
Group.new('@tag.delimiter', colors.gray_3)
Group.new('@type', colors.gray_3)

-- TODO: The ones below need further testing
Group.new('@text.literal', colors.secondary)
Group.new('@text.reference', colors.secondary)
Group.new('@text.title', colors.gray_2)
Group.new('@text.uri', colors.gray_2)
Group.new('@text.underline', colors.gray_2)
Group.new('@text.todo', colors.gray_2)
Group.new('@comment', colors.gray_7)
Group.new('@punctuation', colors.gray_2)
Group.new('@constant', colors.gray_2)
Group.new('@constant.builtin', colors.gray_2)
Group.new('@constant.macro', colors.gray_2)
Group.new('@define', colors.gray_2)
Group.new('@macro', colors.gray_2)
Group.new('@character', colors.secondary)
Group.new('@character.special', colors.gray_2)
Group.new('@number', colors.primary)
Group.new('@boolean', colors.gray_2)
Group.new('@float', colors.gray_2)
Group.new('@function.call', colors.gray_2)
Group.new('@function.builtin', colors.gray_2)
Group.new('@function.macro', colors.primary)
Group.new('@parameter', colors.gray_2)
Group.new('@method.call', colors.gray_2)
Group.new('@field', colors.gray_2)
Group.new('@conditional', colors.gray_2)
Group.new('@repeat', colors.gray_2)
Group.new('@label', colors.gray_2)
Group.new('@operator', colors.gray_6)
Group.new('@exception', colors.gray_2)
Group.new('@variable.builtin', colors.gray_2)
Group.new('@type.definition', colors.gray_2)
Group.new('@storageclass', colors.gray_2)
Group.new('@structure', colors.gray_2)
Group.new('@namespace', colors.gray_2)
Group.new('@preproc', colors.gray_2)
Group.new('@debug', colors.gray_2)
Group.new('@keyword.operator', colors.gray_6)
Group.new('@string', colors.primary)
Group.new('@string.escape', colors.gray_2)
Group.new('@string.special', colors.gray_2)
-- TODO... This section needs work for sure

-- Semantic Highlighting
Group.new('DiagnosticError', colors.diagnostic_error, nil, styles.italic + styles.undercurl)
Group.new('DiagnosticWarn', colors.diagnostic_warning, nil, styles.italic + styles.undercurl)
Group.new('DiagnosticInfo', colors.diagnostic_info, nil, styles.italic + styles.undercurl)
Group.new('DiagnosticHint', colors.diagnostic_hint, nil, styles.italic + styles.undercurl)
Group.new('DiagnosticSignError', colors.diagnostic_error)
Group.new('DiagnosticSignWarn', colors.diagnostic_warning)
Group.new('DiagnosticSignInfo', colors.diagnostic_info)
Group.new('DiagnosticSignHint', colors.diagnostic_hint)
Group.new('DiffAdd', colors.diff_add)
Group.new('DiffChange', colors.diff_change)
Group.new('DiffDelete', colors.diff_delete)
